### ISSUE TITLE
CRUD Users

### ISSUE THREAD

**Issue by gustav0d** [gusgalote/beacademy-devstart-ametista#2]
- [x] Migration 
    - name
    - email
    - phone_number
    - address (maybe create an address table?)
    - birth_date
    - document_id (cpf)
- [x] Model User
- [x] Create
    - [x] View
    - [x] Controller
- [x] Update
    - [x] View
    - [x] Controller
- [x] Delete
    - [x] View
    - [x] Controller
- [x] List
    - [x] View
    - [x] Controller

**Comment by AndersemReis** [comment]
approved.

**Comment by AndersemReis** [comment]
approved
