### ISSUE TITLE
Use standards in Products and Categories

### ISSUE THREAD

**Issue by gustav0d** [gusgalote/beacademy-devstart-ametista#5]
## Frontend
- [x] Use standard layout
    - [x] Default table for crud products (same as crud users)
    - [x] Default table for crud categories (same as crud users)
    - [x] Use a modal to confirm deletion (same as crud users)
        - [x] products
        - [x] categories
- [x] Apply the `dashboard.blade.php` layout to all pages (same as crud users)

## Backend
- [x] Fix products and categories `delete` action
- [x] Use soft delete instead of delete in products and categories
    - [x] Make migrations
    - [x] Change models
    - [x] Change `destroy` method on each Controller
- If you have any doubts, this feature is the same as the one we have in the `User` CRUD
- Remember to see always check the docs https://laravel.com/docs/9.x/eloquent#soft-deleting

**Comment by gustav0d** [comment]
@AndersemReis @minosdavi @avillagabriella  @marcelovins  Precisamos disso pronto essa semana, quem consegue fazer?

**Comment by avillagabriella** [comment]
Já estou fazendo o possível para corrigir os erros do delete e também do layout @gusgalote
